myapp/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from .views import ArticleList, ArticleListBS4
from django.views.generic import TemplateView

from . import views

app_name='myapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.MyView.as_view(),name='myapp-about'),
]

urlpatterns += [
    path('articles/<int:year>/', views.year_archive),
    #path('articles/<int:year>/<int:month>/', views.month_archive),
    #path('articles/<int:year>/<int:month>/<int:pk>/', views.article_detail),
    path('article/<int:pk>/', views.article_details, name="article_details"),
]

urlpatterns += [
    path('art/', ArticleList.as_view()),
    path('art/<int:pk>', views.get_article,name='art-detail'),
    path('artbs4',ArticleListBS4.as_view()),
    #path('your-name/', views.get_name),
    path('your-name/', views.MyFormView.as_view()),
    path('your-namebs4/', views.MyFormView.as_view(template_name='myapp/namebs4.html')),
    path('list/',views.list),
    path('asj/',views.asj),
    path('datatablesdata/',views.DatatablesViewData.as_view(), name="datatablesdata"),
    path('datatables/', views.DatatablesView.as_view()),
    path('tables2/',views.tables2)
]


from myapp.views import AuthorCreate, AuthorDelete, AuthorUpdate
urlpatterns += [
    # ...
    path('author/add/', AuthorCreate.as_view(), name='author-add'),
    path('author/<int:pk>/', AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', AuthorDelete.as_view(), name='author-delete'),
    path('author/view/<int:pk>/', views.author_details, name='author-detail'),
]

from .views import Person, ArticleEdit
urlpatterns += [
    path('person/',views.PersonListView.as_view(),name='myapp-person'),
    path('person/<int:pk>/', views.Person, name='myapp-person-pk'),
    #path('person/<int:pk>/delete/',views.PersonDelete.as_view()),
    path('person/<int:pk>/<str:action>/',views.Person),

    path('article_edit/<int:pk>',views.ArticleEdit),
    path('article_edit/<int:pk>/<str:action>/',views.ArticleEdit),
]

myproj/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.contrib.auth import forms as auth_forms

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('polls/', include('polls.urls')),
    path('ol/', include('ol.urls')),
    path('sitreps/', include('sitreps.urls')),
    path('doc/', include('documents.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path(
        'accounts/change_password/',auth_views.PasswordChangeView.as_view(form_class=auth_forms.SetPasswordForm),
    ),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

myapp/models.py
from django.contrib.auth.models import User
from django.db import models

class Reporter(models.Model):
    full_name = models.CharField(max_length=70)

    def __str__(self):
        return self.full_name

class Article(models.Model):
    pub_date = models.DateField()
    headline = models.CharField(max_length=200)
    content = models.TextField()
    reporter = models.ForeignKey(Reporter, on_delete=models.CASCADE)

    def __str__(self):
        return self.headline


from django.urls import reverse

class Author(models.Model):
    name = models.CharField(max_length=200, default='todd')
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    email = models.EmailField(null=True)

    def get_absolute_url(self):
        return reverse('author-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name


class Person(models.Model):
    SHIRT_SIZES = (
        ('S', 'Small'),
        ('M', 'Medium'),
        ('L', 'Large'),
    )

    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    shirt_size=models.CharField(max_length=1,choices=SHIRT_SIZES)

    def __str__(self):
        return self.last_name+", "+self.first_name

myapp/forms.py
from django import forms

class NameForm(forms.Form):
    your_name = forms.CharField(label='Your name', max_length=100)

### ModelForms
from .models import Person, Article, User

class PersonForm(forms.ModelForm):
    class Meta:
        model=Person
        fields=['id','first_name','last_name','shirt_size']


class TickerForm(forms.ModelForm):
    pub_date=forms.DateField(widget=forms.TextInput(attrs={'type':'date'}))
    class Meta:
        model=Article
        fields=['headline','pub_date','content','reporter']

class ArticleForm(forms.ModelForm):
    class Meta:
        model=Article
        fields=['id','pub_date','headline','content','reporter']

myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from .models import Article
from django.contrib.auth.decorators import login_required
from django.views.generic import View, ListView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin

def index(request, pk=0):
    msg="My App"
    #return HttpResponse("Hello, world. You're at the myapp index.")
    context={'msg': msg}
    return render(request, 'myapp/index.html', context)

from django.views.generic import TemplateView

class AboutView(TemplateView):
    template_name = "myapp/about.html"
    extra_context = {'msg': 'Message goes here...'}

    def get(self, request):
        msg=request.GET.get('msg')
        return render(request, self.template_name,{'msg':msg})



class MyView(View):
    def get(self, request):
        # <view logic>
        return render(request, "myapp/about.html",{'msg':'OK'})

def year_archive(request, year):
    a_list = Article.objects.filter(pub_date__year=year)
    context = {'year': year, 'article_list': a_list}
    return render(request, 'myapp/year_archive.html', context)

@login_required
def article_details(request, pk):
    a = Article.objects.get(id=pk)
    context = {'id': 1, 'article': a}
    #return HttpResponse(context['article'])
    return render(request, 'myapp/article_detail.html', context)

class ArticleList(ListView):
    template_name = 'myapp/article_listBS4.html'
    model = Article
    queryset= Article.objects.all()
    context_object_name = 'articles'
    paginate_by=10

from django.contrib import messages
class ArticleListBS4(ListView):
    template_name = 'myapp/article_list_bs4.html'
    model = Article
    queryset= Article.objects.all()
    context_object_name = 'articles'
    paginate_by=10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #messages.success(self.request, 'Your password was updated successfully!')
        return context

### Forms
from django.http import HttpResponseRedirect
from .forms import NameForm,PersonForm

def get_name(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = NameForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect('/?m=ok')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = NameForm()

    return render(request, 'myapp/name.html', {'form': form})

class MyFormView(View):
    form_class = NameForm
    initial = {'key': 'value'}
    template_name = 'myapp/name.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            # <process form cleaned data>
            return HttpResponseRedirect('/about/?msg=Success')

        return render(request, self.template_name, {'form': form})

from . import models

### Person
def Person(request,pk,action=None):

    success_url="/person"

    if(pk>0):
        instance = models.Person.objects.get(pk=pk)
    else:
        instance = None

    # if this is a POST request we need to process the form data
    if request.method == 'POST':

        # create a form instance and populate it with data from the request:
        if(action=='delete'):
            instance.delete()
            return HttpResponseRedirect(success_url)

        # create a form instance and populate it with data from the request:
        form = PersonForm(request.POST,instance=instance)

        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            form.save()

            # redirect to a new URL:
            return HttpResponseRedirect(success_url)

    # if a GET (or any other method) we'll create a blank form
    else:
        if(action=="delete"):
            #instance = models.Person.objects.get(pk=pk)
            return render(request, 'myapp/confirm_delete.html', {'object': instance,'success_url':success_url})

        form = PersonForm(instance=instance)

    return render(request, 'myapp/person.html', {'form': form, 'rid':pk})

class PersonListView(ListView):

    template_name = 'myapp/person_list.html'
    model = models.Person
    queryset= models.Person.objects.all()
    context_object_name = 'people'
    paginate_by=10

class PersonDelete(DeleteView):
    model = models.Person
    success_url = '/person'
    template_name="myapp/confirm_delete.html"



def get_article(request, pk):
    return HttpResponse("OK")


from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from myapp.models import Author

class AuthorCreate(CreateView):
    model = Author
    fields = ['name','created_by']

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

class AuthorUpdate(UpdateView):
    model = Author
    fields = ['name','created_by','email']

class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('author-list')

def author_details(request, pk):
    a = Author.objects.get(id=pk)
    context = {'id': 1, 'author': a}
    #return HttpResponse(context['article'])
    return render(request, 'myapp/author_detail.html', context)

def list(request):
    a = Article.objects.all()
    context = {'articles': a}
    return render(request, 'myapp/list.html', context)


from django.core import serializers

def asj(request):
    object_list = Article.objects.all() #or any kind of queryset
    json = serializers.serialize('json', object_list)
    return HttpResponse(json, content_type='application/json')


### Datatables
from django_datatables_view.base_datatable_view import BaseDatatableView

class DatatablesViewData(BaseDatatableView):
    model = Article
    columns = ['id','headline','pub_date','reporter']
    order_columns = ['id','headline','pub_date','reporter']
    max_display_length = 500
    template_name = "myapp/datatableview.html"

    def filter_queryset(self, qs):
        # simple example:
        search = self.request.GET.get(u'search[value]', None)
        if search:
            qs = qs.filter(headline__istartswith=search)

        return qs

class DatatablesView(TemplateView):
    template_name = 'myapp/datatables.html'
    headers=['ID','Headline','Pub Date','Reporter']
    extra_context={'headers': headers,'ajax_url':'/datatablesdata'}


### django-tables2

from django_tables2 import RequestConfig
from .tables import ArticleTable

def tables2(request):
    table = ArticleTable(Article.objects.all())
    RequestConfig(request,paginate={'per_page': 10}).configure(table)
    return render(request, 'myapp/tables2.html', {'table': table})


### Article edit
from .forms import ArticleForm

def ArticleEdit(request,pk,action=None):

    success_url="/datatables"

    if(pk>0):
        instance = models.Article.objects.get(pk=pk)
    else:
        instance = None

    # if this is a POST request we need to process the form data
    if request.method == 'POST':

        # create a form instance and populate it with data from the request:
        if(action=='delete'):
            instance.delete()
            return HttpResponseRedirect(success_url)

        # create a form instance and populate it with data from the request:
        form = ArticleForm(request.POST,instance=instance)

        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            form.save()

            # redirect to a new URL:
            return HttpResponseRedirect(success_url)

    # if a GET (or any other method) we'll create a blank form
    else:
        if(action=="delete"):
            #instance = models.Person.objects.get(pk=pk)
            return render(request, 'myapp/confirm_delete.html', {'object': instance,'success_url':success_url})

        form = ArticleForm(instance=instance)

    return render(request, 'myapp/article_edit.html', {'form': form, 'rid':pk})


def picture(request):
    return render(request, 'myapp/picture.html', {})

myapp/templates/myapp/about.html
{% extends 'template.html' %}
{% block content %}
{% load static %}
<h1>About</h1>
{{msg}}
{% url 'myapp:myapp-about' %}
<script src="{% static "js/mgrs.js" %}"></script>
<img src="{% static "parade01.jpg" %}" alt="My image"/>

{% endblock %}

myapp/templates/myapp/article_detail.html
{% extends "template.html" %}

{% block title %}Article{% endblock %}

{% block content %}
<h2>Article</h2>
<p>{{ article.headline }}</p>

  <div class="card">
    <div class="card-body">{{article.content}}</div>
  </div>
<br></br>Author:{{article.reporter}}

{% endblock %}

myapp/templates/myapp/article_edit.html
{% extends "template.html" %}
{% load crispy_forms_tags %}
{% block content %}
<h1>Article - editing</h1>
<form action="{{rid}}" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="hidden" id="id" name="id" value="3">
    <input type="submit" class="btn btn-primary" value="Submit" />
    {% if rid > 0 %}
    <a href="{{rid}}/delete/" class="btn btn-primary" value="Delete" />Delete</a>
    {% endif %}
</form>

<script>
    $('#id_pub_date').width('10em')
    $('#id_reporter').width('15em')
</script>

{% endblock %}

myapp/templates/myapp/article_list.html
{% extends "template.html" %}

{% block content %}
    <h2>Articles</h2>

<table class="table table-bordered table-sm">
  <thead>
    <tr>
      <th>Headline</th>
      <th>Pub Date</th>
    </tr>
  </thead>
  <tbody>
    {% for a in articles %}
      <tr>
        <td><a href="/article/{{a.pk}}">{{ a.headline }}</td>
        <td>{{ a.pub_date|date:'Y-m-d' }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>



    {% if is_paginated %}
    <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-left">
      {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
      {% else %}
      <li class="page-item disabled"><a class="page-link" href="#"><span>&laquo;</span></a></li>
      {% endif %}
      {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
      <li class="page-item active"><a class="page-link" href="#">{{ i }} <span class="sr-only">(current)</span></a></li>
      {% else %}
      <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
      {% else %}
      <li class="page-item disabled"><a class="page-link" href="#"><span>&raquo;</span></a></li>
      {% endif %}
    </ul>
    </nav>
    {% endif %}

{% endblock %}

myapp/templates/myapp/article_list_bs4.html
{% extends 'template.html' %}
{# Load the tag library #}
{% load bootstrap4 %}

{% block content %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_javascript jquery=True %}
{% bootstrap_messages %}

<h2>Articles with BS4 Tags</h2>

<table class="table table-bordered table-sm">
  <thead>
    <tr>
      <th>Headline</th>
      <th>Pub Date</th>
    </tr>
  </thead>
  <tbody>
    {% for a in articles %}
      <tr>
        <td><a href="/article/{{a.pk}}">{{ a.headline }}</td>
        <td>{{ a.pub_date|date:'Y-m-d' }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>

{% bootstrap_pagination page_obj %}

Page {{page_obj.number}} of {{paginator.num_pages}}

{% endblock %}

myapp/templates/myapp/asj.html
<table cellpadding="0" cellspacing="0" border="0" id="example">
     <thead>
         <tr><th>My Attr Heading</th></tr>
     </thead>
     <tbody></tbody>
</table>


<script type="text/javascript" language="javascript" class="init">
     $(document).ready(function() {
         $('#example').dataTable( {
             "processing": true,
             "ajax": {
                 "processing": true,
                 "url": "{% url 'asj' %}",
                 "dataSrc": ""
             },

             "columns": [
                     { "data": "fields.headline },
                     { "data": "pk" }
                 ]
         } );
     } );
 </script>

myapp/templates/myapp/author_form.html
{% extends "template.html" %}
{% load crispy_forms_tags %}
{% block title %}Author{% endblock %}

{% block content %}
<h2>Author - Create</h2>
<div class="container">
    <form action="" method="post">
{% csrf_token %}

 {{ form|crispy}}
    <button type="submit" class="btn btn-primary btn-block">Submit</button>
    <input type="hidden" name="next" value="{{ next }}" />
    </form>
</div>

{% endblock %}

myapp/templates/myapp/index.html
{% extends "template.html" %}

{% block title %}Articles for {{ year }}{% endblock %}

{% block content %}
<h1>Articles for {{ year }}</h1>

{% for article in article_list %}
    <p>{{ article.headline }}</p>
    <p>By {{ article.reporter.full_name }}</p>
    <p>Published {{ article.pub_date|date:"F j, Y" }}</p>
{% endfor %}
{% endblock %}

myapp/templates/myapp/list.html
{% extends "template.html" %}

{% block content %}

<h1>Articles</h1>

<table id="grid-basic" class="table table-condensed table-hover table-striped">

    <thead>
        <tr>
            <th data-column-id="id" data-identifier="true">ID</th>
            <th data-column-id="headline" data-formatter="headline">Headline</th>
        </tr>
    </thead>

    <tbody>
{% for a in articles %}
    <tr>
        <td>{{ a.pk }}</td>
        <td>{{a.headline}}</td>

    </tr>
{% endfor %}
    </tbody>
</table>


<script>
$("#grid-basic").bootgrid({
    formatters: {
        "headline": function (column, row)
        {
            return "<a href=\"/article/" + row["id"] + "\">" + row[column.id] + "</a>";
        }
    }
});
</script>

{% endblock %}

myapp/templates/myapp/namebs4.html
{% extends "template.html" %}
{% load bootstrap4 %}
{% block content %}
<h1>Name Form using django-bootstrap</h1>
<form action="/your-name/" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">
      Submit
    </button>
  {% endbuttons %}

</form>
{% endblock %}

myapp/templates/myapp/person.html
{% extends "template.html" %}
{% load crispy_forms_tags %}
{% block content %}
<form action="/person/{{rid}}/" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="hidden" id="id" name="id" value="3">
    <input type="submit" class="btn btn-primary" value="Submit" />
    {% if rid > 0 %}
    <a href="/person/{{rid}}/delete/" class="btn btn-primary" value="Delete" />Delete</a>
    {% endif %}
</form>
{% endblock %}

myapp/templates/myapp/profile.html
<form method="post">
  {% csrf_token %}
  {{ user_form.as_p }}
  {{ profile_form.as_p }}
  <button type="submit">Save changes</button>
</form>

myapp/templates/myapp/tables2.html
{% extends 'template.html' %}
{% load render_table from django_tables2 %}

{% block content %}

<h1>Articles using Table2</h1>
    {% render_table table %}

<div style="padding:1em">
    <a href="/article_edit/0"/" class="btn btn-primary" role="button">New Article</a>
</div>


<script>
    $('.table').addClass('table-sm table-striped table-bordered')
</script>
{% endblock %}

myapp/templates/myapp/year_archive.html
{% extends "template.html" %}

{% block title %}Articles for {{ year }}{% endblock %}

{% block content %}
<h1>Articles for {{ year }}</h1>

<table class="table">
 <tr><th>Name</th><th>Author</th><th>Pub Date</th></tr>

{% for article in article_list %}
    <tr>
        <td><a href="/article/{{article.pk}}">{{ article.headline }}</a></td>
        <td>By {{ article.reporter.full_name }}</td>
        <td>Published {{ article.pub_date|date:"j b Y"|upper }}</td>
    </tr>
{% endfor %}
</table>

{% endblock %}